version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    ports:
      - "8088:80"
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./public:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge